# -*- coding: utf-8 -*-
"""Grupo 10-Actividad Sumativa Unidad II-Python(con_classv2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynwDJMOJDrN5BfV_YXD7Vn5wTYUR8xAT
"""

promedio = int(0)
class notas:
  notamasalta = ''
  notamasbaja = ''
  dosnotasigualesmayores = ''
  dosnotasigualesmenores = ''
  notasiguales = ''
  promedio = ''
  def imprime_notamasalta(self):
      if (nota2 < nota1 > nota3):
        print("La nota más alta es la primera ingresada, es decir: " + str(nota1))
      if (nota1 < nota2 > nota3):
        print("La nota más alta es la segunda ingresada, es decir: " + str(nota2))
      if (nota1 < nota3 > nota2):
        print("La nota más alta es la tercera ingresada, es decir: " + str(nota3))
      print(self.notamasalta)

  def imprime_notamasbaja(self):
      if (nota2 > nota1 < nota3):
        print("La nota más baja es la primera ingresada, es decir: " + str(nota1))
      if (nota1 > nota2 < nota3):
        print("La nota más baja es la segunda ingresada, es decir: " + str(nota2))
      if (nota1 > nota3 < nota2):
        print("La nota más baja es la tercera ingresada, es decir: " + str(nota3))
      print(self.notamasbaja)
  
  def imprime_dosnotasigualesmayores(self):
      if nota1 == nota2 and (nota1 > nota3) and (nota2 > nota3):
        print("Las notas más altas son la primera y segunda ingresadas, es decir: " + str(nota1) + " y " + str(nota2))
      if nota1 == nota3 and (nota1 > nota2) and (nota3 > nota2):
        print("Las notas más altas son la primera y tercera ingresadas, es decir: " + str(nota1) + " y " + str(nota3))
      if nota2 == nota3 and (nota2 > nota1) and (nota3 > nota1):
        print("Las notas más altas son la segunda y tercera ingresadas, es decir: " + str(nota2) + " y " + str(nota3))
      print(self.dosnotasigualesmayores)
  
  def imprime_dosnotasigualesmenores (self):
      if nota1 == nota2 and (nota1 < nota3) and (nota2 < nota3):
        print("Las notas más bajas son la primera y segunda ingresadas, es decir: " + str(nota1) + " y " + str(nota2))
      if nota1 == nota3 and (nota1 < nota2) and (nota3 < nota2):
        print("Las notas más bajas son la primera y tercera ingresadas, es decir: " + str(nota1) + " y " + str(nota3))
      if nota2 == nota3 and (nota2 < nota1) and (nota3 < nota1):
        print("Las notas más bajas son la segunda y tercera ingresadas, es decir: " + str(nota2) + " y " + str(nota3)) 
      print(self.dosnotasigualesmenores)

  def imprime_promedio(self):
    promedio = round(((float((nota1) + (nota2) + (nota3)) / 3)), 1)
    print("El promedio de sus notas es: " + str(promedio))
  
  def imprime_notasiguales(self):
      if nota1 == nota2 and nota2 == nota3 and nota1 == nota3:
        print("Todas las notas ingresadas son iguales.")
      print(self.notasiguales)

nota1 = float(input("Por favor, ingrese la primera nota: "))
if nota1<float(1.0) or nota1>float(7.0):
  print("Número inválido, ejecute el programa nuevamente e ingrese un valor entre 1 y 7.")
else:
  if nota1 not in [round(nota1, i) for i in[0,1]]:
    print("Número inválido, ejecute el programa nuevamente e ingrese un máximo de 1 decimal.")
  else:
    nota2 = float(input("Por favor, ingrese la segunda nota: "))
    if nota2<float(1.0) or nota2>float(7.0):
      print("Número inválido, ejecute el programa nuevamente e ingrese un valor entre 1 y 7.")
    else:
        if nota2 not in [round(nota2, i) for i in[0,1]]:
          print("Número inválido, ejecute el programa nuevamente e ingrese un máximo de 1 decimal.")
        else:
          nota3 = float(input("Por favor, ingrese la tercera nota: "))
          if nota3<float(1.0) or nota3>float(7.0):
            print("Número inválido, ejecute el programa nuevamente e ingrese un valor entre 1 y 7.")
          else:
            if nota3 not in [round(nota3, i) for i in [0, 1]]:
              print("Número inválido, ejecute el programa nuevamente e ingrese un máximo de 1 decimal.")
            else:
              print("")
              dato=notas()
              dato.imprime_notamasalta()
              dato.imprime_notamasbaja()
              dato.imprime_dosnotasigualesmayores()
              dato.imprime_dosnotasigualesmenores()
              dato.imprime_notasiguales()
              dato.imprime_promedio()